fixes:
  - "ros_ws/src/*/vision_system/::"

ignore:
  - "tests/*"  # Ignore in tests
  - "docs/*"  # Ignore in docs
  - "examples/*"  # Ignore in examples
  - "resource/*"  # Ignore in resource
  - "config/*"  # Ignore in config
  - "launch/*"  # Ignore in launch
  - "setup.py"
